### ISSUE TITLE
Desktop name problem

### ISSUE THREAD

**Issue by cristiansc1993** [mrfreaky123/hwid--spoofer--aka-registry-key-changer#1]
As of windows 10, there are several registry paths missing from the spoofer, some would be:

Computer\HKEY_CURRENT_USER\Volatile Environment -> userdomains

Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Group Policy\DataStore\Machine\0 ->sz's

Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Reliability -> CompName

etc...

**Comment by mrfreaky123** [comment]
this is no longer being updated
